<?php
$cisco_bgp_af_commands = array(
'ensure' => array ('ensure', array('absent', 'present', )),
'asn' => array ('asn', array('<string>', '<integer>', )),
'vrf' => array ('vrf', array('present', 'default', '<string>', )),
'afi' => array ('afi', array()),
'safi' => array ('safi', array()),
'additional paths install' => array ('additional_paths_install', array('true', 'false', 'default', )),
'additional paths receive' => array ('additional_paths_receive', array('true', 'false', 'default', )),
'additional paths selection' => array ('additional_paths_selection', array('<string>', )),
'additional paths send' => array ('additional_paths_send', array('true', 'false', 'default', )),
'advertise l2vpn evpn' => array ('advertise_l2vpn_evpn', array('true', 'false', )),
'client to client' => array ('client_to_client', array('true', 'false', )),
'dampen igp metric' => array ('dampen_igp_metric', array('default', '<integer>', )),
'dampening state' => array ('dampening_state', array('true', 'false', 'default', )),
'dampening half time' => array ('dampening_half_time', array('default', '<integer>', )),
'dampening max suppress time' => array ('dampening_max_suppress_time', array('default', '<integer>', )),
'dampening reuse time' => array ('dampening_reuse_time', array('default', '<integer>', )),
'dampening routemap' => array ('dampening_routemap', array('<string>', )),
'dampening suppress time' => array ('dampening_suppress_time', array('default', '<integer>', )),
'default information originate' => array ('default_information_originate', array('true', 'false', )),
'default metric' => array ('default_metric', array('default', '<integer>', )),
'distance ebgp' => array ('distance_ebgp', array('default', '<integer>', )),
'distance ibgp' => array ('distance_ibgp', array('default', '<integer>', )),
'distance local' => array ('distance_local', array('default', '<integer>', )),
'inject map' => array ('inject_map', array('<string>', )),
'maximum paths' => array ('maximum_paths', array('default', '<integer>', )),
'maximum paths ibgp' => array ('maximum_paths_ibgp', array('default', '<integer>', )),
'networks' => array ('networks', array('<string>', )),
'next hop route map' => array ('next_hop_route_map', array('<string>', )),
'redistribute' => array ('redistribute', array('<string>', )),
'suppress inactive' => array ('suppress_inactive', array('true', 'false', 'default', )),
'table map' => array ('table_map', array('<string>', )),
'table map filter' => array ('table_map_filter', array('true', 'false', 'default', )),
);
?>