<?php
$cisco_interface_commands = array(
'ensure' => array ('ensure', array('absent', 'present', )),
'interface' => array ('interface', array('<string>', )),
'channel group' => array ('channel_group', array('default', )),
'description' => array ('description', array('default', '<string>', )),
'duplex' => array ('duplex', array('auto', 'full', )),
'speed' => array ('speed', array('auto', )),
'shutdown' => array ('shutdown', array('andndefault', 'true', 'false', 'default', )),
'switchport mode' => array ('switchport_mode', array('disabled', 'fexfabric', 'default', 'tunnel', 'access', 'trunk', )),
'ip acl in' => array ('ipv4_acl_in', array('default', '<string>', )),
'ip acl out' => array ('ipv4_acl_out', array('default', '<string>', )),
'ipv6 acl in' => array ('ipv6_acl_in', array('default', '<string>', )),
'ipv6 acl out' => array ('ipv6_acl_out', array('default', '<string>', )),
'access vlan' => array ('access_vlan', array('default', 'keywordndefault', '<integer>', )),
'encapsulation dot1q' => array ('encapsulation_dot1q', array('default', '<integer>', )),
'mtu' => array ('mtu', array('<integer>', )),
'switchport autostate exclude' => array ('switchport_autostate_exclude', array('true', 'false', 'default', )),
'switchport trunk allowed vlan' => array ('switchport_trunk_allowed_vlan', array('default', '<string>', )),
'switchport trunk native vlan' => array ('switchport_trunk_native_vlan', array('default', '<integer>', )),
'switchport vtp' => array ('switchport_vtp', array('true', 'false', 'default', 'falsenand', )),
'negotiate auto' => array ('negotiate_auto', array('true', 'false', 'default', 'truenfalse', )),
'ip pim sparse mode' => array ('ipv4_pim_sparse_mode', array('true', 'false', 'default', )),
'ip proxy arp' => array ('ipv4_proxy_arp', array('true', 'false', 'default', )),
'ip redirects' => array ('ipv4_redirects', array('true', 'false', 'default', )),
'ip address' => array ('ipv4_address', array('default', '<string>', )),
'ip netmask length' => array ('ipv4_netmask_length', array('default', '<integer>', )),
'ip address secondary' => array ('ipv4_address_secondary', array('default', '<string>', )),
'ip netmask length secondary' => array ('ipv4_netmask_length_secondary', array('default', '<integer>', )),
'ip arp timeout' => array ('ipv4_arp_timeout', array('default', '<string>', '<integer>', )),
'vlan mapping' => array ('vlan_mapping', array('default', '<string>', )),
'vlan mapping enable' => array ('vlan_mapping_enable', array('true', 'false', 'default', )),
'vrf' => array ('vrf', array('default', '<string>', )),
'svi autostate' => array ('svi_autostate', array('true', 'false', 'default', 'truenfalse', )),
'svi management' => array ('svi_management', array('true', 'false', 'default', )),
);
?>