<?php
$cisco_bgp_neighbor_af_commands = array(
'ensure' => array ('ensure', array('absent', 'present', )),
'asn' => array ('asn', array('<string>', '<integer>', )),
'vrf' => array ('vrf', array('present', 'default', '<string>', )),
'neighbor' => array ('neighbor', array('<string>', )),
'afi' => array ('afi', array('<string>', )),
'safi' => array ('safi', array('<string>', )),
'advertise map exist' => array ('advertise_map_exist', array('myexistmap', 'default', '<string>', 'myadvertisemap', )),
'advertise map non exist' => array ('advertise_map_non_exist', array('mynonexistmap', 'default', '<string>', 'myadvertisemap', )),
'allowas in' => array ('allowas_in', array('true', 'false', '<integer>', )),
'allowas in max' => array ('allowas_in_max', array('default', '<integer>', )),
'as override' => array ('as_override', array('true', 'false', 'default', )),
'additional paths receive' => array ('additional_paths_receive', array()),
'additional paths send' => array ('additional_paths_send', array()),
'default originate' => array ('default_originate', array('true', 'false', 'default', )),
'default originate route map' => array ('default_originate_route_map', array('default', '<string>', )),
'filter list in' => array ('filter_list_in', array('default', '<string>', )),
'filter list out' => array ('filter_list_out', array('default', '<string>', )),
'max prefix limit' => array ('max_prefix_limit', array('default', '<integer>', )),
'max prefix interval' => array ('max_prefix_interval', array('default', '<integer>', )),
'max prefix threshold' => array ('max_prefix_threshold', array('default', '<integer>', )),
'max prefix warning' => array ('max_prefix_warning', array('true', 'false', 'default', )),
'next hop self' => array ('next_hop_self', array('true', 'false', 'default', )),
'next hop third party' => array ('next_hop_third_party', array('true', 'false', 'default', )),
'prefix list in' => array ('prefix_list_in', array('default', '<string>', )),
'prefix list out' => array ('prefix_list_out', array('default', '<string>', )),
'route map in' => array ('route_map_in', array('default', '<string>', )),
'route map out' => array ('route_map_out', array('default', '<string>', )),
'route reflector client' => array ('route_reflector_client', array('true', 'false', 'default', )),
'send community' => array ('send_community', array('extended', 'standard', 'default', 'none', 'both', )),
'soft reconfiguration in' => array ('soft_reconfiguration_in', array()),
'soo' => array ('soo', array('default', '<string>', )),
'suppress inactive' => array ('suppress_inactive', array('true', 'false', 'default', )),
'unsuppress map' => array ('unsuppress_map', array('default', '<string>', )),
'weight' => array ('weight', array('default', '<integer>', )),
);
?>